services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./sample_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  geoserver:
    image: docker.osgeo.org/geoserver:2.27.1
    container_name: geoserver
    ports:
      - "8080:8080"
    volumes:
      - ./data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=ogcapi-features
    restart: unless-stopped
    depends_on:
      - db

  setup:
    image: curlimages/curl:latest
    container_name: geoserver_setup
    depends_on:
      - geoserver
    volumes:
      - ./geoserver_setup:/scripts
    entrypoint: ["/bin/sh", "/scripts/setup.sh"]
